#!/bin/sh

PRIMARY_DISPLAY=eDP1
AUX_DISPLAY=DP2

if xrandr -q | grep "$AUX connected"; then
    xrandr --output $PRIMARY_DISPLAY --auto
    xrandr --output $AUX_DISPLAY --auto --same-as $PRIMARY_DISPLAY
else
    xrandr --output $PRIMARY_DISPLAY --auto
    xrandr --output $AUX_DISPLAY --off
fi
