#!/bin/sh

PRIMARY_DISPLAY=eDP1
AUX_DISPLAY=DP2
DOCKPATT=DP-1-1- #*

if xrandr -q | grep "$AUX_DISPLAY connected"; then
    xrandr --output $PRIMARY_DISPLAY --auto
    xrandr --output $AUX_DISPLAY --auto --same-as $PRIMARY_DISPLAY
elif xrandr -q | grep "$DOCKPATT" | grep " connected"; then
    echo "Mirror dock"
    ~/.screenlayout/mirrorDock.sh
else
    xrandr --output $PRIMARY_DISPLAY --auto
    xrandr --output $AUX_DISPLAY --off
fi

# Set again wallpaper
exec feh --bg-center /home/agutierrez/Pictures/fondopantalla

