#!/bin/sh

PRIMARY_DISPLAY=eDP1
AUX_DISPLAY=DP2

if xrandr -q | grep "$AUX_DISPLAY connected"; then
    xrandr --output $PRIMARY_DISPLAY --auto --primary
    xrandr --output $AUX_DISPLAY --auto --right-of $PRIMARY_DISPLAY
else
    xrandr --output $PRIMARY_DISPLAY --auto --primary
    xrandr --output $AUX_DISPLAY --off
fi
