#!/bin/sh

PRIMARY_DISPLAY=eDP1
AUX_DISPLAY=DP2
DOCKPATT=DP-1-1- #*


if xrandr -q | grep "$AUX_DISPLAY connected"; then
    xrandr --output $PRIMARY_DISPLAY --auto --primary
    xrandr --output $AUX_DISPLAY --auto --right-of $PRIMARY_DISPLAY
elif xrandr -q | grep "$DOCKPATT" | grep " connected"; then
    echo "Dual dock"
    ~/.screenlayout/dualDock.sh
else
    xrandr --output $PRIMARY_DISPLAY --auto --primary
    xrandr --output $AUX_DISPLAY --off
fi
